### ISSUE TITLE
FLAT_001B Selection screen

### ISSUE THREAD

**Issue by jtscherko** [sw20-tug/ASD-Afternoon-3#19]
If more than one flat exist and no flat is selected as current flat, the selection screen should appear. (see FLAT_004)

**Acceptance criteria:**

-> Screen, which shows all existing flats
-> Select the requested one and open it

**Comment by tuchris** [comment]
no list of flats is existing at this point?

**Comment by petritz** [comment]
This was wrongly added to the 001 issue.
