### ISSUE TITLE
FLAT_003C All flats screen

### ISSUE THREAD

**Issue by jtscherko** [sw20-tug/ASD-Afternoon-3#23]
Overview of all flats which are set up. User can add or remove flat from his "own flat" list. Most important information of every flat is shown as well.

**Acceptance Criteria:**
-> All flats are shown
-> Ability to remove/add flat to "own flat" list
-> Bullet points of every flat can be seen

**Comment by petritz** [comment]
During a meeting we found out that this issue was not necessary (003B is already descriping the scenario)
