### ISSUE TITLE
FLAT_004 Select current flat

### ISSUE THREAD

**Issue by sw20-tugraz** [sw20-tug/ASD-Afternoon-3#4]
As a user I want to select one flat as my current flat to skip the beginning flat selection screen. At start I want to see the overview window of my current selected flat.

**Acceptance criteria:**
- Selecting one flat as the one you are currently in
- Skip flat selection screen at start up and load start screen with info of current (related to FLAT_001)

**Comment by g4e817** [comment]
![issue_4](https://user-images.githubusercontent.com/62063593/78123490-851f3300-740e-11ea-934f-b1cfbe310797.PNG)
