### ISSUE TITLE
FLAT_005 Roommates

### ISSUE THREAD

**Issue by sw20-tugraz** [sw20-tug/ASD-Afternoon-3#5]
As a user I want to be able to add, delete or rename information about my roommates.

**Acceptance criteria:**
- Each flat should provide a list of all roommates
- Adding, deleting and renaming

**Comment by g4e817** [comment]
![issue_5_1](https://user-images.githubusercontent.com/62063593/78123534-949e7c00-740e-11ea-8e5e-8b55e1e66063.PNG)
![issue_5_2](https://user-images.githubusercontent.com/62063593/78123535-96683f80-740e-11ea-839c-550ab3be411b.PNG)
